# Generated by Django 4.0 on 2021-12-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
                ('profile_url', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=500, null=True)),
                ('twitter_url', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('avatar_url', models.CharField(max_length=200, null=True)),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devfindapp.keyword', verbose_name='The related query for this user')),
            ],
        ),
    ]
